---
abstract: 'Installation of Perl bindings to RRDtool'
author:
  - 'Fuji, Goro (gfx) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::CBuilder: '0'
  File::ShareDir: '0'
  Test::More: '0.88'
  Test::Requires: '0.06'
configure_requires:
  File::Which: '0'
  File::chdir: '0'
  LWP::Simple: '0'
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-RRDtool
no_index:
  directory:
    - inc
    - author
requires:
  File::ShareDir: '1.00'
  perl: '5.008001'
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
